version: '3.9'

services:

  db:
    image: postgres
    restart: always
    
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=base


 