version: '3.9'

services:
  bibliotecapp:
    container_name: bibliotec_back_container
    build: ./back
    image: back_bibliotec:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - internalnet

    
    
    depends_on:
      - db
    environment:
      - Docs=/docs
      - User=root
      - Host=db
      - Database=bibliotec
      - Pass=1234
      - Port=5432
      - Key_Key=Dy7oFm9z!L2k@1ePwQ8R4m3NvX6sG3tH2jU0iK5oP7mN4bF1wE9rQ8yH3aSñ
      - origin=http://0.0.0.0:4200
    
  db:
    image: postgres
    
    shm_size: 128mb
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host

    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bibliotec
    networks:
      - internalnet
    

  bibliotecapp_frontend:
    container_name: bibliotec_container
    build: ./web
    image: bibliotec:latest
    ports:
      - "4200:80"
      - target: 4200
        published: 4200
        protocol: tcp
        mode: host
    expose:
      - "4200"
    networks:
      - internalnet
    depends_on:
      - bibliotecapp
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bibliotecapp_frontend.entrypoints=http"
        - "traefik.http.routers.bibliotecapp_frontend.rule=Host(`biblioteca.byronrm.com`)"
        - "traefik.http.middlewares.bibliotecapp_frontend-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.bibliotecapp_frontend.middlewares=portainer-https-redirect"
        - "traefik.http.routers.bibliotecapp_frontend-secure.entrypoints=https"
        - "traefik.http.routers.bibliotecapp_frontend-secure.rule=Host(`biblioteca.byronrm.com`)"
        - "traefik.http.routers.bibliotecapp_frontend-secure.tls=true"
        - "traefik.http.routers.bibliotecapp_frontend-secure.tls.certresolver=http"
        - "traefik.http.routers.bibliotecapp_frontend-secure.service=bibliotecapp_frontend"
        - "traefik.http.services.bibliotecapp_frontend.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"

    
networks:
  internalnet:
    driver: bridge
    external: true 


# scp Escritorio/proyecto_int/Proy/stack.yml root@161.97.140.245:/root/herramientas_docker/biblioteca_test/Proy
# scp Escritorio/proyecto_int/Proy/makefile root@161.97.140.245:/root/herramientas_docker/biblioteca_test/Proy