


services:
  bibliotecapp:
    container_name: bibliotec_back_container
    build: .
    image: back_bibliotec:latest
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
    #docker-compose up 