# version: '3.8'

# services:
#   app:
#     image: back_bibliotec:local
#     container_name: back_container
#     build: 
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#     - 3000:3000
#     volumes:
#     - .:/app

#     # docker build -t nest-test .


services:
  bibliotecapp:
    container_name: bibliotec_back_container
    build: .
    image: back_bibliotec:latest
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
    #docker-compose up 