services:
  bibliotecapp:
    container_name: bibliotec_container
    build: .
    image: bibliotec:latest
    ports:
      - 4201:80
    expose:
      - 4201
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
    #docker-compose up 